insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Zamit', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Home Ing', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Temp', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Sub-Ex', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Rank', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Cardify', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Overhold', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Zamit', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Lotlux', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Subin', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Overhold', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'fix San', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Kanlam', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Home Ing', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Biodex', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Alphazap', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Tempsoft', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Span', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Wrapsafe', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Tres-Zap', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Sonair', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Transcof', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'fixflex', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Alpha', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Quo Lux', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Sonsing', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Temp', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Voyatouch', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Bytecard', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Voltsillam', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Zamit', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Zamit', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Treeflex', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'fixflex', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'fix San', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Cardify', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Lotstring', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Zamit', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Daltfresh', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Zathin', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Prodder', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Zathin', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Zathin', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Lotstring', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Prodder', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Alpha', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'It', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'fintone', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Vagram', false);
insert into ticket_types (id, `name`, is_deleted) values (UUID_TO_BIN(UUID()), 'Namfix', false);
