insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Zamit', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Home Ing', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Temp', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Sub-Ex', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Rank', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Cardify', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Overhold', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Zamit', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Lotlux', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Subin', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Overhold', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'fix San', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Kanlam', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Home Ing', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Biodex', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Alphazap', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Tempsoft', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Span', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Wrapsafe', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Tres-Zap', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Sonair', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Transcof', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'fixflex', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Alpha', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Quo Lux', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Sonsing', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Temp', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Voyatouch', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Bytecard', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Voltsillam', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Zamit', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Zamit', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Treeflex', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'fixflex', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'fix San', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Cardify', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Lotstring', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Zamit', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Daltfresh', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Zathin', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Prodder', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Zathin', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Zathin', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Lotstring', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Prodder', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Alpha', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'It', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'fintone', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Vagram', false, 5);
insert into ticket_types (id, `name`, is_deleted, quantity) values (UUID_TO_BIN(UUID()), 'Namfix', false, 5);
