INSERT INTO event_event_type (id, event_id, event_type_id, is_deleted)
VALUES
    (UUID_TO_BIN(UUID()), (SELECT id FROM events ORDER BY RAND() LIMIT 1), (SELECT id FROM event_types ORDER BY RAND() LIMIT 1), FALSE),
    (UUID_TO_BIN(UUID()), (SELECT id FROM events ORDER BY RAND() LIMIT 1), (SELECT id FROM event_types ORDER BY RAND() LIMIT 1), FALSE),
    (UUID_TO_BIN(UUID()), (SELECT id FROM events ORDER BY RAND() LIMIT 1), (SELECT id FROM event_types ORDER BY RAND() LIMIT 1), FALSE),
    (UUID_TO_BIN(UUID()), (SELECT id FROM events ORDER BY RAND() LIMIT 1), (SELECT id FROM event_types ORDER BY RAND() LIMIT 1), FALSE),
    (UUID_TO_BIN(UUID()), (SELECT id FROM events ORDER BY RAND() LIMIT 1), (SELECT id FROM event_types ORDER BY RAND() LIMIT 1), FALSE),
    (UUID_TO_BIN(UUID()), (SELECT id FROM events ORDER BY RAND() LIMIT 1), (SELECT id FROM event_types ORDER BY RAND() LIMIT 1), FALSE),
    (UUID_TO_BIN(UUID()), (SELECT id FROM events ORDER BY RAND() LIMIT 1), (SELECT id FROM event_types ORDER BY RAND() LIMIT 1), FALSE);
